--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.12.2018 12:35:31
-- Server version: 5.7.16-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO dergiyonetimsistemi.editor(editorid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, calistigiil, calistigiilce) VALUES
(1, 'gencay', 'gencay', 'ay', 'gencay756@gmail.com', '05314821512', '123', '123', 'Tekirdag', 'Merkez');
INSERT INTO dergiyonetimsistemi.editor(editorid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, calistigiil, calistigiilce) VALUES
(2, 'aaa', 'dfg', 'dfg', 'dfg', '22222222', 'rrr', 'rrr', 'Ordu', 'merkez');