--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.12.2018 12:35:32
-- Server version: 5.7.16-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO dergiyonetimsistemi.hakem(hakemid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik) VALUES
(1, 'elif', 'elif', 'akkus', 'elif@gmail.com', '02222222222', '123', '123', 'donanim');
INSERT INTO dergiyonetimsistemi.hakem(hakemid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik) VALUES
(2, 'dfg', 'dfg', 'dfg', 'dfg', '3333', 'dfg', 'dfg', 'yazilim');
INSERT INTO dergiyonetimsistemi.hakem(hakemid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik) VALUES
(3, 'ayse', 'ayse', 'ince', 'sdfsd', '2222', '123', '123', 'yazilim');
INSERT INTO dergiyonetimsistemi.hakem(hakemid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik) VALUES
(4, 'canan', 'Canan', 'Tastimur', 'genc4y10@gmail.com', '22222222', '123', '123', 'bilgisyar');