--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.12.2018 12:35:33
-- Server version: 5.7.16-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(3, 'ayse', 'wer', 'asd', 'genc4y10@gmail.com', '22222222', '14', '14', 'yazar', 2, 'bilggisayar', 'Yildiz Teknik Universitesi', 'Makine Muhendisligi', 'IL Seciniz..', '');
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(7, 'rr', 'rr', 'rr', 'genc4y10@gmail.com', '22222222', '123', '123', 'yazar', 2, 'bilggisayar', 'Istanbul Teknik Universitesi', 'Elektrik Elektronik Muhendisligi', 'IL Seciniz..', '');
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(8, 'qq', 'qq', 'qq', 'genc4y10@gmail.com', '22222222', 'qq', 'qq', 'hakem', 3, 'bilggisayar', 'Okul Seciniz..', 'Bolum Seciniz..', 'IL Seciniz..', '');
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(9, 'aaa', 'aaa', 'aaa', 'genc4y10@gmail.com', '22222222', 'aa', 'aa', 'editor', 1, '', 'Okul Seciniz..', 'Bolum Seciniz..', 'Ordu', 'merkez');
INSERT INTO dergiyonetimsistemi.kayitlar(kayitid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, unvan, unvanid, uzmanlikalani, okul, bolum, calistigiil, calistigiilce) VALUES
(10, 'yy', 'yy', 'yy', 'genc4y10@gmail.com', '22222222', 'yy', 'yy', 'hakem', 3, 'bilggisayar', 'Okul Seciniz..', 'Bolum Seciniz..', 'IL Seciniz..', '');