--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.12.2018 12:35:34
-- Server version: 5.7.16-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('aaa', 'rrr', 1);
INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('ayse', '123', 2);
INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('canan', '123', 3);
INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('dfg', 'dfg', 3);
INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('elif', '123', 3);
INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('furkan', '123', 2);
INSERT INTO dergiyonetimsistemi.login(kullaniciadi, sifre, unvanid) VALUES
('gencay', '123', 1);