--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.12.2018 12:35:37
-- Server version: 5.7.16-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO dergiyonetimsistemi.yazar(yazarid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik, okul, bolum) VALUES
(1, 'ayse', 'ayse', 'ince', 'ayse@gmail.com', '02222222222', '123', '123', 'bilgisayar,yazilim', 'Fırat Universitesi', 'Bilgisayar Muhendisligi');
INSERT INTO dergiyonetimsistemi.yazar(yazarid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik, okul, bolum) VALUES
(2, 'asd', 'asd', 'asd', 'asd', '22222222', 'asd', 'asd', 'asd', 'Yildiz Teknik Universitesi', 'Elektrik Elektronik Muhendisligi');
INSERT INTO dergiyonetimsistemi.yazar(yazarid, kullaniciadi, ad, soyad, email, telno, sifre, sifretekrar, uzmanlik, okul, bolum) VALUES
(3, 'furkan', 'furkan', 'uyar', 'genc4y10@gmail.com', '05314821512', '123', '123', 'grafik', 'Firat Universitesi', 'Bilgisayar Muhendisligi');